#             parados.conf
# This is the parados configuration file.
# Manual available at parados.conf(5)

# *General*

# Directory containing media files.
#media_dir=/var/media
media_dir=/path/to/media

# Address to bind the HTTP server to.
# Use 0.0.0.0 to listen on all interfaces.
#
# It is recommended to bind on 127.0.0.1 and
# host the WebUI on the same network if you
# are using one.
#
#server_addr=127.0.0.1
server_addr=0.0.0.0

# TCP port to listen on.
server_port=8088

# Enable verbose logging information.
#verbose_log=false
verbose_log=true

# *Security*

# Cross-Origin Resource Sharing (CORS).
#
# Controls which web origins may access the API.
#
# Empty value disables CORS.
# "*" allows all origins (not recommended).
# Otherwise, specify a comma separated list of allowed origins.
#
#cors_origin=http://127.0.0.1:8000
cors_origin=

# *Resource Limits*

# HTTP IO timeout (in seconds).
#
# Limits how long the server will block on a single socket read/write.
# This does not apply for requests/streaming.
# If a client stops sending data or stops reading responses for longer
# than this value, the connection is dropped.
#
# Recommended:  LAN=5, WAN/VPN/Mobile=15-30
http_io_timeout=5

# Max Clients
#
# Limits the maximum number of simultaneous client connections
# handled by the server.
max_clients=64

# *Authentication*

# Each entry consists of one `user`, `pass`, and (multiple) `allow` directives.
# Multiple users are permitted.
#
# For example:
#
#   user=glenda
#   pass=pass123
#   allow=Media/
#   allow=Music/
#
#   user=bob
#   pass=
#   allow=TV/NBA/
#
# is valid.
#
# `pass` may be empty to disable authentication for that entry.
#
# `allow` specifies which directories a user is permitted to access.
# Use "*" to allow all directories, or multiple `allow` lines with
# each directory specified.
user=admin
pass=
allow=*

