#	parados.conf
# This is the parados configuration file.
# See parados(1) for more information.

# Core configuration
#
# Directory containing media files.
#media_dir=/var/media
media_dir=/path/to/media

# Address to bind the HTTP server to.
# Use 0.0.0.0 to listen on all interfaces.
#
# It is recommended to bind on 127.0.0.1 and
# host the WebUI on the same network if you
# are using one
#
#bind_addr=127.0.0.1
bind_addr=0.0.0.0

# TCP port to listen on.
bind_port=8088

# Logging
#
# Enable verbose logging.
#verbose_log=false
verbose_log=true

# Cross-Origin Resource Sharing (CORS)
#
# Controls which web origins may access the API.
#
# Empty value disables CORS.
# "*" allows all origins (not recommended).
# Otherwise, specify a comma separated list of allowed origins.
#
#cors_origin=http://127.0.0.1:8000
cors_origin=

